### ISSUE TITLE
Django3.0 compatibility- dependancy on django.utils.six

### ISSUE THREAD

**Issue by PaulSHahn** [reecetech/django_informixdb#20]
Installed driver in Python3 virtualenv via pip (from pypy). Created Django project and application. Edited setup.py and exported requested variables mentioned in the ReadMe to my environment. Tested via command: 
python manage dbshell 
```
Traceback (most recent call last):

  File "/home/phahn2/CXManagementService/server/umenv/lib/python3.7/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/phahn2/CXManagementService/server/umenv/lib/python3.7/site-packages/django_informixdb/base.py", line 19, in <module>
    from django.utils.six import binary_type, text_type
ModuleNotFoundError: No module named 'django.utils.six'

The above exception was the direct cause of the following exception:
...

django.core.exceptions.ImproperlyConfigured: 'django_informixdb' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
```

Apparently django.utils.six is no longer a thing in the latest django release...

**Comment by floatingpurr** [comment]
Same here. Did you fix it?
